### ISSUE TITLE
Rendering a line series with 1 data point causes exception when tapping to show tooltip

### ISSUE THREAD

**Issue by muzzah** [syncfusion/flutter-widgets#123]
I have Cartesian chart as below with a single data point

<img width="590" alt="Screen Shot 2021-01-22 at 22 51 58" src="https://user-images.githubusercontent.com/1034537/105552644-8191cb00-5d04-11eb-9049-2696b7e48eef.png">

Now when I tap on the dot to show the tooltip I get the error below 

```
======== Exception caught by rendering library =====================================================
The following RangeError was thrown during paint():
RangeError (index): Invalid value: Valid value range is empty: 0

The relevant error-causing widget was: 
  SfCartesianChart file:///Users/nobunaga/Workspace/Siia/siia/lib/teacher_session/widescreen/insights/class_insights_widget.dart:254:16
When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:177:60)
#1      _TooltipPainter._renderTooltip (package:syncfusion_flutter_charts/src/chart/user_interaction/tooltip_painter.dart:700:36)
#2      TooltipBehaviorRenderer.onPaint (package:syncfusion_flutter_charts/src/common/user_interaction/tooltip.dart:883:16)
#3      _TooltipPainter.paint (package:syncfusion_flutter_charts/src/chart/user_interaction/tooltip_painter.dart:673:46)
#4      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:531:13)
...
```

Also, sometimes the number above the data points do not render and I have to refresh the widgets and redraw it for the lines and numbers to render properly.

<img width="595" alt="Screen Shot 2021-01-22 at 22 53 39" src="https://user-images.githubusercontent.com/1034537/105552774-b2720000-5d04-11eb-86fd-ba1658c351ef.png">

**Comment by Dharanipalani** [comment]
Hi @muzzah,

We can replicate your reported scenario at our end and we regret the inconvenience. We will resolve this and include it in the next weekly patch release which is expected to be rolled out on the 1st week of February 2021. Please be patience until then.

Thanks,
Dharanitharan. P

**Comment by Dharanipalani** [comment]
Hi @muzzah,
 
We are happy to inform you that the reported issue has been fixed in our latest version **v18.4.41**. Now the tooltip for a single data point will render and does not throw any exception. Please upgrade our chart package to the latest version from the following link.
 
Latest version:  [https://pub.dev/packages/syncfusion_flutter_charts/versions/18.4.41 ](url)
 
Thanks,
Dharanitharan. P

**Comment by muzzah** [comment]
@JayavigneshwaranG While the exception seems to be fixed, I still always do not get the graph to render properly on first display and therefore I cannot tap the data point to show the tooltip. I have to refresh the screen for the numbers to render which then allows me to tap to display the tooltip. Please see my original comment about this, was this fixed?

**Comment by muzzah** [comment]
I take it you guys are not going to fix the other issue mentioned?

**Comment by kestasb** [comment]
We're using syncfusion_flutter_charts: ^19.2.59 and the app is still crashing with the following stack trace:

```
error: RangeError (index): Invalid value: Valid value range is empty: 0, stackTrace: #0      List.[] (dart:c
#1      TooltipBehaviorRenderer._tooltipRenderingEvent (package:syncfusion_flutter_charts/src/common/user_in
#2      TooltipRenderBox.paint (package:syncfusion_flutter_core/src/tooltip/tooltip.dart:513:46)<…>
#3      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)<…>
#4      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)<…>
#5      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2795:15)<…>
#6      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)<…>
#7      RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)<…>
#8      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)<…>
#9      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)<…>
#10     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)<…>
#11     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2162:11)<…>
#12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)<…>
#13     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)<…>
#14     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)<…>
#15     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2162:11)<…>
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)<…>
#17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)<…>
#18     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:140:15)<…>
#19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2317:7)<…>
#20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:13)<…>
```

This issue occurs only if we use onTooltipRender: (TooltipArgs args) => {}. Otherwise, a default tooltip is displayed without crashing. @Dharanipalani We'd appreciate it if you could look into this issue for the next plugin update.
