### ISSUE TITLE
Error: Couldn't find constructor 'TextScaler.linear'.

### ISSUE THREAD

**Issue by pen110** [syncfusion/flutter-widgets#1544]
../.pub-cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-23.2.5/lib/src/common/template/rendering.dart:401:9: Error: A constant constructor can't call a non-constant super constructor.

syncfusion_flutter_charts: ^23.2.5

**Comment by cyberail** [comment]
We fixed it by keeping, 23.2.4 version without carrot symbol, so it will not upgrade.

```yaml
syncfusion_flutter_datepicker: 23.2.4
```

**Comment by pen110** [comment]
Error (Xcode):
../.pub-cache/hosted/pub.flutter-io.cn/syncfusion_flutter_charts-23.2.4/lib/src/common/template/r
endering.dart:401:9: Error: A constant constructor can't call a non-constant super constructor.

but 23.2.4 This version is still wrong

**Comment by pen110** [comment]
SfCartesianChart It's not in the plugin if I use syncfusion_flutter_datepicker: 23.2.4

**Comment by KalaliEhsan** [comment]
You should upgrade Flutter SDK to the latest version and resolve this issue. @pen110

**Comment by pen110** [comment]
I'd like to upgrade, but I can't, flutter sdk 3.7.8 is mine, There are other items that do not need to be upgraded

**Comment by LokeshPalani** [comment]
Hi,



We have analyzed your query and checked the reported issue. We would like to inform you that the textScaleFactor property has been deprecated to the textScaler property from Flutter 3.16.0. Our packages are now compatible with the 3.16 version. To resolve the mentioned issue regarding "The getter 'textScaler' isn't defined for the 'MediaQueryData'", we suggest upgrading the Flutter SDK to the latest version.



Regards,
Lokesh P.

**Comment by LokeshPalani** [comment]
Hi @trevorFields,



We would like to inform you that you can use our Syncfusion_flutter_charts package version 22.2.12. It is compatible with flutter SDK version 3.13.8. By using this Syncfusion_flutter_charts package, you can avoid updating to the latest flutter SDK version.



Regards,
Lokesh P.

**Comment by marah126** [comment]
cupertino_icons: ^1.0.2
  calendar_view: ^1.0.4
  syncfusion_flutter_calendar: ^23.1.41
  intl: ^0.18.1
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  path: ^1.8.3
  http_parser: ^4.0.2
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  path_provider: ^2.1.1
  syncfusion_localizations: ^23.2.7
  flutter_localization: ^0.2.0
  firebase_messaging: ^14.7.10
  rxdart: ^0.27.7
  syncfusion_flutter_charts: ^23.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  open_file: ^3.2.1

i have these packages and i have this error on syncfusion_flutter_charts  
../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-23.2.7/lib/src/chart/base/chart_base.dart:1838:33: Error: Couldn't find constructor 'TextScaler.linear'.
              textScaler: const TextScaler.linear(1.2),
                                ^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-23.2.7/lib/src/chart/base/chart_base.dart:1838:15: Error: No named parameter with the name 'textScaler'.
              textScaler: const TextScaler.linear(1.2),
              ^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/text.dart:428:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/syncfusion_flutter_charts-23.2.7/lib/src/common/utils/helper.dart:965:33: Error: Couldn't find constructor 'TextScaler.linear'.
              textScaler: const TextScaler.linear(1.2),
                                ^^^^^^ 

I am using flutter version 3.16.3
how to resolve problem?

**Comment by LavanyaGowtham2021** [comment]
Please reopen this ticket with requested details, if you still face an issue with latest charts version.

**Comment by mit291997** [comment]
Please use 20.4.54 solved in 3.88.0 flutter version.
