### ISSUE TITLE
Trackball Overlapping after Flutter Upgrade

### ISSUE THREAD

**Issue by lsrmg** [syncfusion/flutter-widgets#2205]
### Bug description

After upgrading Flutter to 3.27.0 (from 3.24.4) the Z-axis for the Trackball are not working correctly anymore. 
The same issue is present for Crosshair Tooltips for example.

(updating syncfusion_flutter_charts from 27.1.53 to 28.1.33 didn't resolve the issue)

### Steps to reproduce

1. Upgrading to flutter 3.27.0

### Code sample

<details open><summary>Code sample</summary>

```dart
SfCartesianChart(
              plotAreaBorderColor: theme.colorScheme.pmBarBackground,
              plotAreaBorderWidth: 1,
              zoomPanBehavior: ZoomPanBehavior(
                  enableDoubleTapZooming: true,
                  zoomMode: ZoomMode.x,
                  enablePinching: true),
              trackballBehavior: TrackballBehavior(
                  enable: true,
                  activationMode: ActivationMode.singleTap,
                  tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
                  tooltipSettings: InteractiveTooltip(
                      enable: true,
                      format: 'point.y ${chartData.firstOrNull?.unit ?? ''}',
                      borderWidth: 1,
                      borderColor: theme.colorScheme.onSurface,
                      textStyle: TextStyle(color: theme.colorScheme.onSurface),
                      color: theme.colorScheme.surface)),
              primaryXAxis: DateTimeAxis(
                  dateFormat: timeFormat24hSetting.when(
                    data: (is24h) =>
                        is24h ? chartTimeFormat24h : chartTimeFormat12h,
                    loading: () => chartTimeFormat12h,
                    error: (_, __) => chartTimeFormat12h,
                  ),
                  interactiveTooltip: InteractiveTooltip(
                      arrowLength: 0,
                      // Enables the crosshair tooltip
                      enable: true)),
              primaryYAxis: NumericAxis(
                  majorGridLines:
                      MajorGridLines(color: theme.colorScheme.pmBarBackground),
                  interactiveTooltip: InteractiveTooltip(
                      // Disables the crosshair tooltip
                      enable: false)),
              legend: Legend(isVisible: true, position: LegendPosition.bottom),
              // Enable tooltip
              series: <CartesianSeries>[
                FastLineSeries<ChartData, DateTime>(
                    dataSource: chartData,
                    xValueMapper: (ChartData data, _) => data.date,
                    yValueMapper: (ChartData data, _) => data.value,
                    emptyPointSettings:
                        const EmptyPointSettings(mode: EmptyPointMode.average),
                    name: dataLegend,
                    color: theme.colorScheme.pmLineChartColor1,
                    // Duration of series animation
                    animationDuration: 500),
                if (secondDataLegend != '')
                  FastLineSeries<ChartData, DateTime>(
                    dataSource: secondChartData,
                    xValueMapper: (ChartData data, _) => data.date,
                    yValueMapper: (ChartData data, _) => data.value,
                    emptyPointSettings:
                        const EmptyPointSettings(mode: EmptyPointMode.average),
                    name: secondDataLegend,
                    color: theme.colorScheme.pmLineChartColor2,
                    // Duration of series animation
                    animationDuration: 500,
                  )
              ],
            ),
```

</details>

### Screenshots or Video

<details open>
<summary>Video demonstration</summary>

https://github.com/user-attachments/assets/2034f2a4-2ffe-4b54-af6a-eb9620a517fd

</details>

### Stack Traces

<details open><summary>Stack Traces</summary>

```dart
-```

</details>


### On which target platforms have you observed this bug?

Android, iOS

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.27.0, on macOS 15.2 24C101 darwin-arm64, locale en-US)
    • Flutter version 3.27.0 on channel stable at /Users/lars/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (3 days ago), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /Users/lars/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/to/macos-android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 16.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16C5032a
    • CocoaPods version 1.15.2

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google
    Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2024.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)

[✓] VS Code (version 1.96.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.102.0

[✓] Connected device (4 available)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

</details>

**Comment by lsrmg** [comment]
Problem is solved after downgrading to Flutter 3.24.5 (still using updating syncfusion_flutter_charts 28.1.33)

**Comment by Shunt22** [comment]
It's not just trackball. 
After upgrading to Flutter 3.27.0 here is AlertDialog overlapping with LineSeries on Android 13. 
![image](https://github.com/user-attachments/assets/a6edabb0-99d5-4e73-921a-408bccd06c88)

**Comment by Kaviyarasansf4298** [comment]
Hi @Shunt22,

We have checked the mentioned scenario and tried to replicate the reported issue regarding the Trackball overlapping in the SfCartesianChart widget with the updated SDK version 3.27.0. However, we were unable to reproduce the issue on our end. We have attached the sample we used to test the scenario. Please review the attached sample, and if you are still encountering the issue, we kindly request that you replicate it in the attached sample and provide us with additional details about the specific scenario in which the issue occurs. This will help us assist you more effectively.

Regards,
Kaviyarasan Arumugam.

[bd_667955](https://support.syncfusion.com/agent/tickets/667955)

[bd_667955.zip](https://github.com/user-attachments/files/18196885/bd_667955.zip)

**Comment by Shunt22** [comment]
Hi!
I've slightly modified your code. Adding up to 4096 points to LineSeries and the bug is still happening.
![image](https://github.com/user-attachments/assets/b289b310-9bf1-4bee-adda-c41383ebf58e)

Here is the code:
```
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'charts_tooltip',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(),
    );
  }
}

class ChartData {
  final DateTime date;
  final double value;
  final String unit;

  ChartData(this.date, this.value, {this.unit = ''});
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({
    super.key,
  });

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  late List<ChartData> chartData;
  late List<ChartData> secondChartData;
  String dataLegend = "Series 1";

  @override
  void initState() {
    super.initState();
    chartData = [];

    for (int i = 0; i < 4096; ++i) {
      chartData.add(
        ChartData(DateTime.now().add(Duration(days: i)), i.toDouble(),
            unit: "°C"),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      floatingActionButton: FloatingActionButton(onPressed: () async {
        String? res = await showDialog(
          context: context,
          builder: (context) {
            return AlertDialog(
              content: Container(
                width: 100,
                height: 100,
                child: Text("I'm overlapping"),
              ),
            );
          },
        );
      }),
      appBar: AppBar(
        title: const Text('Syncfusion Chart Example'),
      ),
      body: Center(
        child: SfCartesianChart(
          plotAreaBorderColor: theme.colorScheme.surface,
          plotAreaBorderWidth: 1,
          zoomPanBehavior: ZoomPanBehavior(
            enableDoubleTapZooming: true,
            zoomMode: ZoomMode.x,
            enablePinching: true,
          ),
          trackballBehavior: TrackballBehavior(
            enable: true,
            activationMode: ActivationMode.longPress,
            tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
            tooltipSettings: InteractiveTooltip(
              enable: true,
              format: 'point.y ${chartData.firstOrNull?.unit ?? ''}',
              borderWidth: 1,
              borderColor: theme.colorScheme.onSurface,
              textStyle: TextStyle(color: theme.colorScheme.onSurface),
              color: theme.colorScheme.surface,
            ),
          ),
          primaryXAxis: DateTimeAxis(
            dateFormat: DateFormat('MM/dd/yyyy'),
            interactiveTooltip: const InteractiveTooltip(
              arrowLength: 0,
              enable: true,
            ),
          ),
          primaryYAxis: NumericAxis(
            majorGridLines: MajorGridLines(color: theme.colorScheme.surface),
            interactiveTooltip: const InteractiveTooltip(
              enable: false,
            ),
          ),
          legend:
              const Legend(isVisible: true, position: LegendPosition.bottom),
          series: <CartesianSeries>[
            FastLineSeries<ChartData, DateTime>(
              dataSource: chartData,
              xValueMapper: (ChartData data, _) => data.date,
              yValueMapper: (ChartData data, _) => data.value,
              emptyPointSettings:
                  const EmptyPointSettings(mode: EmptyPointMode.average),
              name: dataLegend,
              color: theme.colorScheme.primary,
              animationDuration: 500,
            ),
          ],
        ),
      ),
    );
  }
}

```

> Hi @Shunt22,
> 
> We have checked the mentioned scenario and tried to replicate the reported issue regarding the Trackball overlapping in the SfCartesianChart widget with the updated SDK version 3.27.0. However, we were unable to reproduce the issue on our end. We have attached the sample we used to test the scenario. Please review the attached sample, and if you are still encountering the issue, we kindly request that you replicate it in the attached sample and provide us with additional details about the specific scenario in which the issue occurs. This will help us assist you more effectively.
> 
> Regards, Kaviyarasan Arumugam.
> 
> [bd_667955](https://support.syncfusion.com/agent/tickets/667955)
> 
> [bd_667955.zip](https://github.com/user-attachments/files/18196885/bd_667955.zip)

**Comment by lsrmg** [comment]
> We have checked the mentioned scenario and tried to replicate the reported issue regarding the Trackball overlapping in the SfCartesianChart widget with the updated SDK version 3.27.0. However, we were unable to reproduce the issue on our end. We have attached the sample we used to test the scenario. Please review the attached sample, and if you are still encountering the issue, we kindly request that you replicate it in the attached sample and provide us with additional details about the specific scenario in which the issue occurs. This will help us assist you more effectively.

Thanks for looking into this.

I pasted your code into an iOS App and the issue is present like in my example above. On Android the problem is also present. I tested it also on real devices and the behavior is the same.


https://github.com/user-attachments/assets/41161ce1-5414-4b35-a8db-386b112e9c5d

![Simulator Screenshot - iPhone 16 Pro - 2024-12-20 at 11 28 33](https://github.com/user-attachments/assets/b939bb19-442a-4caa-b3a5-ad6ed42276ea)

**Comment by lsrmg** [comment]
@Kaviyarasansf4298 Thanks a lot for the quick response and the fast rollout of the fix!

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @lsrmg ,



We have validated the reported issue on our end and found that it is a framework-level issue involving an incorrect depth value for the [drawPoints](https://api.flutter.dev/flutter/dart-ui/Canvas/drawPoints.html) method in the canvas with line and polygon [PointMode](https://api.flutter.dev/flutter/dart-ui/PointMode.html). This issue has been acknowledged and fixed by the Flutter team. 

 

In Charts, we used the drawPoints method with [PointMode](https://api.flutter.dev/flutter/dart-ui/PointMode.html).polygon to render a [FastLineSeries](https://pub.dev/documentation/syncfusion_flutter_charts/latest/charts/FastLineSeries-class.html), enabling the rendering of a large number of data points with high performance. You can track the issue using the links below. 

 

Issue report link: https://github.com/flutter/flutter/issues/160343

Issue fix: https://github.com/flutter/engine/pull/56494

 

However, you can resolve this with the help of disabling the impeller in your project. Please refer to the following link to disable the impeller.

 

iOS: https://docs.flutter.dev/perf/impeller#ios

Android: https://docs.flutter.dev/perf/impeller#android

macOS: https://docs.flutter.dev/perf/impeller#macos

 

We will notify you once the reported issue is fixed and moved to the stable channel by the Flutter team.


Thanks,
Yuvaraj.

**Comment by Yuvaraj-Gajaraj** [comment]
Hi @lsrmg ,

The reported issue of the z-axis depth in the drawPoints method point mode as polygon has been fixed and included in the Flutter 3.27.2 SDK and we ensured that it works fine.
 
Please upgrade the Flutter SDK version to the latest 3.27.2 to avoid the issue. If you have any more questions, please feel free to let us know we are always happy to help you.
 
3.27.1:
<img src="https://github.com/user-attachments/assets/439b9be7-43c0-4505-9e5f-5379f9b57095" width=200px, height=400px/>

3.27.2:
<img src="https://github.com/user-attachments/assets/881cf533-410d-4359-a3ae-4c8673f293d9" width=200px, height=400px/>
 
Thanks,
Yuvaraj.

**Comment by Shunt22** [comment]
The issue indeed seems to be resolved.
Thank you!

**Comment by lsrmg** [comment]
The issue is solved for me too.

Thanks a lot!
