### ISSUE TITLE
[syncfusion_flutter_charts] FastLineSeries: not showing when all values are 0 (zero) + wrong trackballDetails.groupingModeInfo.currentPointIndices + index not in inclusive range

### ISSUE THREAD

**Issue by WieFel** [syncfusion/flutter-widgets#861]
When comparing a chart that has a normal `LineSeries` vs a `FastLineSeries`, I noticed various serious problems with `FastLineSeries`:

1. if a series has only 0-values or close-to-0-values, then the `FastLineSeries` is not showing up, while the normal `LineSeries` does (using the same values).
`LineSeries`:
![image](https://user-images.githubusercontent.com/8345062/186388316-4afe9392-dc7e-4d18-ab1d-ee5a715098b3.png)
`FastLineSeries`:
![image](https://user-images.githubusercontent.com/8345062/186388234-ed6a0980-3a53-4b00-9651-c5fd8aba25ed.png)
2. When moving the trackball and showing the tooltip: trackballDetails.groupingModeInfo.currentPointIndices contains the wrong index, which lets my custom tooltip show incorrect information. This problem doesn't happen when I exchange `FastLineSeries` with `LineSeries`.
3. When moving the trackball and showing the tooltip: various `Invalid value: Not in inclusive range` errors:
```
The following RangeError was thrown while handling a gesture:
RangeError (index): Invalid value: Not in inclusive range 0..97: 151

When the exception was thrown, this was the stack: 
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      TrackballRenderingDetails._getLeastX (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:1359:23)
#2      TrackballRenderingDetails._validateNearestXValue (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:1305:20)
#3      TrackballRenderingDetails.generateAllPoints (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:1116:7)
#4      TrackballRenderingDetails.showTemplateTrackball (package:syncfusion_flutter_charts/src/chart/user_interaction/trackball.dart:826:5)
#5      ContainerArea._performLongPressMoveUpdate (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:3414:41)
#6      ContainerArea.build.<anonymous closure>.<anonymous closure> (package:syncfusion_flutter_charts/src/chart/base/chart_base.dart:2496:27)
#7      LongPressGestureRecognizer._checkLongPressMoveUpdate.<anonymous closure> (package:flutter/src/gestures/long_press.dart:756:85)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#9      LongPressGestureRecognizer._checkLongPressMoveUpdate (package:flutter/src/gestures/long_press.dart:756:11)
#10     LongPressGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/long_press.dart:652:9)
#11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:563:9)
#12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:94:12)
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:139:9)
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:137:18)
#16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:123:7)
#17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:445:19)
#18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#27     _invoke1 (dart:ui/hooks.dart:170:10)
#28     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#29     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 3 frames from dart:async)
Handler: "onLongPressMoveUpdate"
Recognizer: LongPressGestureRecognizer#90592
  debugOwner: GestureDetector
  state: possible
```

2. and 3. could be related with each other I suppose.

All of the problems are resolved if I exchange `FastLineSeries` with `LineSeries`. This implies that something must be wrong with `FastLineSeries` in the 3 mentioned situations. I tried to debug it myself, but couldn't get to any solution yet, as the code is quite complex.

**Comment by SriramKiranSenthilkumar** [comment]
Hi @WieFel,

We can replicate the reported issue at our end, and we have logged a bug report for the issue. We will include the fix for the bug in our Volume 3 main release which is expected to be rolled by end of September and we appreciate your patience until then.


Regards,
Sriram Kiran

**Comment by WieFel** [comment]
@SriramKiranSenthilkumar can you push the fix to the master branch of [this repo](https://github.com/syncfusion/flutter-widgets)? I am running a fork of this repo and need to get it fixed as soon as possible.
Or could you otherwise please report here what the fix for the problem is? I suppose it should be a small fix...

**Comment by SriramKiranSenthilkumar** [comment]
Hi Team

For the ‘FastLineSeries not rendering when all values of the data points are the same' bug fix, we would like to let you know that we are already working on Volume 3 main release backlogs at our end. However, we will consider the reported issue as a high priority and will include the fix in our Volume 3 main release, and we appreciate your patience until then.

Query: wrong trackballDetails.groupingModeInfo.currentPointIndices + index not in inclusive range

We have checked your query at our end, and we tried to replicate the reported issues. Unfortunately, we wouldn't be able to reproduce the reported issue. We tried the following scenarios to reproduce the issue in the test phase.

Ensured the fast line series with a large number (say 2000) of closely rendered data points and used the trackball feature to move along the data points to check whether the `currentPointIndices` values of the `trackballDetails.groupingModeInfo` is correct or not.

Ensured the fast line series with a large number of closely rendered data points and moved the trackball back and forth to replicate the invalid exception.

As we don’t know the exact data points values for which the issues are occurring, we kindly request you to modify the below-attached sample with your data points to replicate the reported issue and revert us so that it will help assist you in a better way.

Test sample: [ghfw_861.zip](https://github.com/syncfusion/flutter-widgets/files/9433257/ghfw_861.zip)

Regards,
Sriram Kiran

**Comment by WieFel** [comment]
Regarding the bug about the incorrect index of `trackballDetails.groupingModeInfo`:
The bug seems to appear only when using `TrackballBehavior` with `builder` and a `FastLineSeries` as series.
Strangely, the y-axis' `labelFormat` influences whether the bug appears or not, which I totally don't understand.

I could reproduce the bug in a simple example which I will share here:
<details>
  <summary>Example to reproduce the bug</summary>

```dart
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:syncfusion_flutter_charts/charts.dart';

void main() {
  return runApp(_ChartApp());
}

class _ChartApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(primarySwatch: Colors.blue),
      home: _MyHomePage(),
    );
  }
}

class _MyHomePage extends StatefulWidget {
  // ignore: prefer_const_constructors_in_immutables
  _MyHomePage({Key? key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<_MyHomePage> {
  List<_ChartData> data = [
    _ChartData(1661896800, 1),
    _ChartData(1661897100, 0),
    _ChartData(1661897400, 0),
    _ChartData(1661897700, 0),
    _ChartData(1661898000, 0),
    _ChartData(1661898300, 0),
    _ChartData(1661898600, 0),
    _ChartData(1661898900, 0),
    _ChartData(1661899200, 0),
    _ChartData(1661899500, 0),
    _ChartData(1661899800, 0),
    _ChartData(1661900100, 0),
    _ChartData(1661900400, 0),
    _ChartData(1661900700, 0),
    _ChartData(1661901000, 0),
    _ChartData(1661901300, 0),
    _ChartData(1661901600, 0),
    _ChartData(1661901900, 0),
    _ChartData(1661902200, 0),
    _ChartData(1661902500, 0),
    _ChartData(1661902800, 0),
    _ChartData(1661903100, 0),
    _ChartData(1661903400, 0),
    _ChartData(1661903700, 0),
    _ChartData(1661904000, 0),
    _ChartData(1661904300, 0),
    _ChartData(1661904600, 0),
    _ChartData(1661904900, 1),
    _ChartData(1661905200, 0),
    _ChartData(1661905500, 0),
    _ChartData(1661905800, 0),
    _ChartData(1661906100, 0),
    _ChartData(1661906400, 0),
    _ChartData(1661906700, 0),
    _ChartData(1661907000, 0),
    _ChartData(1661907300, 0),
    _ChartData(1661907600, 0),
    _ChartData(1661907900, 0),
    _ChartData(1661908200, 0),
    _ChartData(1661908500, 0),
    _ChartData(1661908800, 0),
    _ChartData(1661909100, 0),
    _ChartData(1661909400, 0),
    _ChartData(1661909700, 0),
    _ChartData(1661910000, 0),
    _ChartData(1661910300, 0),
    _ChartData(1661910600, 0),
    _ChartData(1661910900, 0),
    _ChartData(1661911200, 0),
    _ChartData(1661911500, 0),
    _ChartData(1661911800, 0),
    _ChartData(1661912100, 0),
    _ChartData(1661912400, 0),
    _ChartData(1661912700, 0),
    _ChartData(1661913000, 0),
    _ChartData(1661913300, 0),
    _ChartData(1661913600, 0),
    _ChartData(1661913900, 0),
    _ChartData(1661914200, 0),
    _ChartData(1661914500, 0),
    _ChartData(1661914800, 0),
    _ChartData(1661915100, 0),
    _ChartData(1661915400, 0),
    _ChartData(1661915700, 0),
    _ChartData(1661916000, 0),
    _ChartData(1661916300, 0),
    _ChartData(1661916600, 1),
    _ChartData(1661916900, 0),
    _ChartData(1661917200, 0),
    _ChartData(1661917500, 0),
    _ChartData(1661917800, 0),
    _ChartData(1661918100, 0),
    _ChartData(1661918400, 0),
    _ChartData(1661918700, 0),
    _ChartData(1661919000, 0),
    _ChartData(1661919300, 0),
    _ChartData(1661919600, 0),
    _ChartData(1661919900, 0),
    _ChartData(1661920200, 0),
    _ChartData(1661920500, 0),
    _ChartData(1661920800, 0),
    _ChartData(1661921100, 0),
    _ChartData(1661921400, 0),
    _ChartData(1661921700, 1),
    _ChartData(1661922000, 0),
    _ChartData(1661922300, 0),
    _ChartData(1661922600, 0),
    _ChartData(1661922900, 0),
    _ChartData(1661923200, 0),
    _ChartData(1661923500, 0),
    _ChartData(1661923800, 0),
    _ChartData(1661924100, 0),
    _ChartData(1661924400, 0),
    _ChartData(1661924700, 0),
    _ChartData(1661925000, 0),
    _ChartData(1661925300, 0),
    _ChartData(1661925600, 0),
    _ChartData(1661925900, 0),
    _ChartData(1661926200, 0),
    _ChartData(1661926500, 0),
    _ChartData(1661926800, 0),
    _ChartData(1661927100, 0),
    _ChartData(1661927400, 0),
    _ChartData(1661927700, 0),
    _ChartData(1661928000, 0),
    _ChartData(1661928300, 0),
    _ChartData(1661928600, 0),
    _ChartData(1661928900, 0),
    _ChartData(1661929200, 0),
    _ChartData(1661929500, 0),
    _ChartData(1661929800, 0),
    _ChartData(1661930100, 0),
    _ChartData(1661930400, 0),
    _ChartData(1661930700, 0),
    _ChartData(1661931000, 0),
    _ChartData(1661931300, 0),
    _ChartData(1661931600, 0),
    _ChartData(1661931900, 0),
    _ChartData(1661932200, 0),
    _ChartData(1661932500, 0),
    _ChartData(1661932800, 0),
    _ChartData(1661933100, 0),
    _ChartData(1661933400, 0),
    _ChartData(1661933700, 0),
    _ChartData(1661934000, 0),
    _ChartData(1661934300, 0),
    _ChartData(1661934600, 0),
    _ChartData(1661934900, 0),
    _ChartData(1661935200, 0),
    _ChartData(1661935500, 0),
    _ChartData(1661935800, 0),
    _ChartData(1661936100, 0),
    _ChartData(1661936400, 0),
    _ChartData(1661936700, 0),
    _ChartData(1661937000, 0),
    _ChartData(1661937300, 0),
    _ChartData(1661937600, 0),
    _ChartData(1661937900, 0),
    _ChartData(1661938200, 0),
    _ChartData(1661938500, 0),
    _ChartData(1661938800, 0),
    _ChartData(1661939100, 0),
    _ChartData(1661939400, 0),
    _ChartData(1661939700, 0),
    _ChartData(1661940000, 0),
    _ChartData(1661940300, 0),
    _ChartData(1661940600, 0),
    _ChartData(1661940900, 0),
    _ChartData(1661941200, 0),
    _ChartData(1661941500, 0),
    _ChartData(1661941800, 0),
    _ChartData(1661942100, 0),
    _ChartData(1661942400, 0),
    _ChartData(1661942700, 0),
    _ChartData(1661943000, 0),
    _ChartData(1661943300, 0),
    _ChartData(1661943600, 0),
    _ChartData(1661943900, 0),
    _ChartData(1661944200, 0),
    _ChartData(1661944500, 0),
    _ChartData(1661944800, 0),
    _ChartData(1661945100, 0),
    _ChartData(1661945400, 0),
    _ChartData(1661945700, 0),
    _ChartData(1661946000, 0),
    _ChartData(1661946300, 0),
    _ChartData(1661946600, 0),
    _ChartData(1661946900, 1),
    _ChartData(1661947200, 0),
    _ChartData(1661947500, 0),
    _ChartData(1661947800, 0),
    _ChartData(1661948100, 0),
    _ChartData(1661948400, 0),
    _ChartData(1661948700, 0),
    _ChartData(1661949000, 0),
    _ChartData(1661949300, 0),
    _ChartData(1661949600, 0),
    _ChartData(1661949900, 0),
    _ChartData(1661950200, 0),
    _ChartData(1661950500, 0),
    _ChartData(1661950800, 0),
    _ChartData(1661951100, 0),
    _ChartData(1661951400, 0),
    _ChartData(1661951700, 0),
    _ChartData(1661952000, 0),
    _ChartData(1661952300, 0),
    _ChartData(1661952600, 0),
    _ChartData(1661952900, 0),
    _ChartData(1661953200, 0),
    _ChartData(1661953500, 0),
    _ChartData(1661953800, 0),
    _ChartData(1661954100, 0),
    _ChartData(1661954400, 0),
    _ChartData(1661954700, 0),
    _ChartData(1661955000, 0),
    _ChartData(1661955300, 0),
    _ChartData(1661955600, 0),
    _ChartData(1661955900, 0),
    _ChartData(1661956200, 0),
    _ChartData(1661956500, 1),
    _ChartData(1661956800, 0),
    _ChartData(1661957100, 0),
    _ChartData(1661957400, 0),
    _ChartData(1661957700, 0),
    _ChartData(1661958000, 0),
    _ChartData(1661958300, 0),
    _ChartData(1661958600, 1),
    _ChartData(1661958900, 0),
    _ChartData(1661959200, 0),
    _ChartData(1661959500, 0),
    _ChartData(1661959800, 0),
    _ChartData(1661960100, 0),
    _ChartData(1661960400, 0),
    _ChartData(1661960700, 0),
    _ChartData(1661961000, 0),
    _ChartData(1661961300, 0),
    _ChartData(1661961600, 0),
    _ChartData(1661961900, 0),
    _ChartData(1661962200, 0),
    _ChartData(1661962500, 0),
    _ChartData(1661962800, 0),
    _ChartData(1661963100, 0),
    _ChartData(1661963400, 0),
    _ChartData(1661963700, 0),
    _ChartData(1661964000, 0),
    _ChartData(1661964300, 0),
    _ChartData(1661964600, 0),
    _ChartData(1661964900, 0),
    _ChartData(1661965200, 0),
    _ChartData(1661965500, 0),
    _ChartData(1661965800, 0),
    _ChartData(1661966100, 0),
    _ChartData(1661966400, 0),
    _ChartData(1661966700, 0),
    _ChartData(1661967000, 1),
    _ChartData(1661967300, 0),
    _ChartData(1661967600, 0),
    _ChartData(1661967900, 0),
    _ChartData(1661968200, 0),
    _ChartData(1661968500, 0),
    _ChartData(1661968800, 0),
    _ChartData(1661969100, 0),
    _ChartData(1661969400, 1),
    _ChartData(1661969700, 0),
    _ChartData(1661970000, 0),
    _ChartData(1661970300, 0),
    _ChartData(1661970600, 0),
    _ChartData(1661970900, 0),
    _ChartData(1661971200, 0),
    _ChartData(1661971500, 0),
    _ChartData(1661971800, 1),
    _ChartData(1661972100, 0),
    _ChartData(1661972400, 0),
    _ChartData(1661972700, 0),
    _ChartData(1661973000, 0),
    _ChartData(1661973300, 0),
    _ChartData(1661973600, 0),
    _ChartData(1661973900, 0),
    _ChartData(1661974200, 0),
    _ChartData(1661974500, 0),
    _ChartData(1661974800, 0),
    _ChartData(1661975100, 0),
    _ChartData(1661975400, 0),
    _ChartData(1661975700, 0),
    _ChartData(1661976000, 0),
    _ChartData(1661976300, 0),
    _ChartData(1661976600, 0),
    _ChartData(1661976900, 0),
    _ChartData(1661977200, 0),
    _ChartData(1661977500, 0),
    _ChartData(1661977800, 0),
    _ChartData(1661978100, 0),
    _ChartData(1661978400, 0),
    _ChartData(1661978700, 0),
    _ChartData(1661979000, 0),
    _ChartData(1661979300, 0),
    _ChartData(1661979600, 0),
    _ChartData(1661979900, 0),
    _ChartData(1661980200, 0),
    _ChartData(1661980500, 0),
    _ChartData(1661980800, 0),
    _ChartData(1661981100, 0),
    _ChartData(1661981400, 0),
    _ChartData(1661981700, 0),
    _ChartData(1661982000, 0),
    _ChartData(1661982300, 0),
    _ChartData(1661982600, 0),
    _ChartData(1661982900, 0),
    _ChartData(1661983200, 0),
  ];

  @override
  Widget build(BuildContext context) {
    var xMin = DateTime.fromMillisecondsSinceEpoch(data.first.x * 1000);
    var xMax = DateTime.fromMillisecondsSinceEpoch(data.last.x * 1000);

    return Scaffold(
        appBar: AppBar(
          title: const Text('Syncfusion Flutter chart'),
        ),
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: SfCartesianChart(
              primaryXAxis: DateTimeAxis(
                dateFormat: DateFormat("HH:mm"),
                minimum: xMin,
                visibleMinimum: xMin,
                maximum: xMax,
                visibleMaximum: xMax,
              ),
              primaryYAxis: NumericAxis(
                // BUG: strangely, this line influences whether the tooltip is
                // getting the correct index for the points information to be
                // displayed within the tooltip.
                // "{value}" as labelFormat works, "{value} abc" breaks the tooltip
                labelFormat: "{value} abc",
              ),
              trackballBehavior: TrackballBehavior(
                enable: true,
                activationMode: ActivationMode.longPress,
                tooltipDisplayMode: TrackballDisplayMode.groupAllPoints,
                builder: (context, trackballDetails) => Card(
                  child: SizedBox(
                    width: 50,
                    height: 50,
                    child: Column(
                      children: [
                        Text(DateFormat("HH:mm").format(
                            trackballDetails.groupingModeInfo!.points.first.x)),
                        Text(
                            "${trackballDetails.groupingModeInfo!.points.first.y}"),
                      ],
                    ),
                  ),
                ),
              ),
              series: <ChartSeries<_ChartData, DateTime>>[
                FastLineSeries<_ChartData, DateTime>(
                  dataSource: data,
                  xValueMapper: (_ChartData sales, _) =>
                      DateTime.fromMillisecondsSinceEpoch(sales.x * 1000),
                  yValueMapper: (_ChartData sales, _) => sales.y,
                  name: 'Sales',
                )
              ],
            ),
          ),
        ));
  }
}

class _ChartData {
  _ChartData(this.x, this.y);

  final int x;
  final double y;
}
```
</details>

So there are the following observations:
- y-axis `labelFormat: "{value}"` works, using a `FastLineSeries`
- **y-axis `labelFormat: "{value} abc"` doesn't work, using a `FastLineSeries`** (might need more letters than just "abc" to be appended, as it might somehow depend on the length)
- y-axis `labelFormat: "{value}"` works, using a `LineSeries`
- y-axis `labelFormat: "{value} abc"` works, using a `LineSeries`

**Comment by SriramKiranSenthilkumar** [comment]
> Hi Team
> 
> For the ‘FastLineSeries not rendering when all values of the data points are the same' bug fix, we would like to let you know that we are already working on Volume 3 main release backlogs at our end. However, we will consider the reported issue as a high priority and will include the fix in our Volume 3 main release, and we appreciate your patience until then.
> 
> 

Hi @WieFel,

We would like to let you know that the reported issue regarding the fast-line series not rendering for same y values and on further analyzing on the issue, we found that the issue is occurring due to using of flutter framework’s drawPoints method to render the fast-line series in the canvas in our source.

However, we are glad to let you know that this issue is fixed in the latest version of flutter SDK ([3.3.1](https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.3.1-stable.zip)). So, we kindly request you to upgrade the flutter SDK version to latest version to resolve the reported issue and also upgrade the chart widget package version to the latest version([20.2.49](https://pub.dev/packages/syncfusion_flutter_charts/versions/20.2.49)).

Regards,
Sriram Kiran

**Comment by WieFel** [comment]
@SriramKiranSenthilkumar thank you for the information.
Again, I would like to know if you will also push these fixes to this repository? As I am working on a fork of it...
So a new release on pub.dev doesn't help me at all...

**Comment by SriramKiranSenthilkumar** [comment]
Hi @WieFel,

We would like to let you know that we will update the changes to this repository only for our main releases. We would like to let you know that we have scheduled our volume 3 main release at end of September.

However, as we mentioned earlier, the issue occurred in flutter framework level and now in their latest version of SDK ([3.3.1](https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.3.1-stable.zip)) its fixed. So, we  request you to upgrade the flutter SDK in your end to overcome the issue at your end.

Regards,
Sriram Kiran

**Comment by WieFel** [comment]
Thanks!

**Comment by WieFel** [comment]
> Example to reproduce the bug

> Screenshots with working/not working example

Running Flutter 3.3.2, unfortunately I can still reproduce the issue from the example above.
So, without updating anything on the chart package side, and only updating Flutter, the issue still persists.

I will wait for the main release of the end of september then and report back.

**Comment by LavanyaGowtham2021** [comment]
Please reopen this, if you need any further assistance on this.
